/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "var(--accent-color, #beee00)",
        "primary-container": "var(--accent-bright, #cafd00)",
        "primary-dim": "var(--accent-dim, #beee00)",
        "secondary-dim": "#ff734a",
        "surface-container-highest": "#262626",
        "on-primary-container": "#4a5e00",
        "surface-bright": "#2c2c2c",
        "primary": "#f3ffca",
        "on-surface": "#ffffff",
        "error": "#ff7351",
        "secondary": "#ff734a",
        "outline": "#767575",
        "surface-container-lowest": "#000000",
        "surface-variant": "#262626",
        "surface-container-low": "#131313",
        "on-primary": "#516700",
        "outline-variant": "#484847",
        "surface": "#0e0e0e",
        "inverse-surface": "#fcf9f8",
        "inverse-primary": "#516700",
        "on-primary-fixed": "#3a4a00",
        "on-tertiary": "#665800",
        "background": "var(--bg-primary, #0e0e0e)",
        "on-secondary": "#430c00",
        "surface-dim": "#0e0e0e",
        "primary-fixed": "#cafd00",
        "on-background": "var(--text-primary, #ffffff)",
        "on-surface-variant": "#adaaaa",
        "error-container": "#b92902",
        "surface-container-high": "#20201f",
        "secondary-container": "#b02f00",
        "tertiary": "#ffeea5",
        "tertiary-fixed": "#fce047",
        "tertiary-fixed-dim": "#edd13a",
        "tertiary-dim": "#edd13a",
        "surface-container": "#1a1a1a",
        "on-secondary-container": "#fff6f4",
        // Landing page light-mode tokens
        "electric-lime": "#CCFF00",
        "landing-surface": "#F8F9FF",
        "landing-on-surface": "#151C25",
        "landing-muted": "#656464",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
        space: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
