/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // ── Stitch "Kinetic Luminescence" design tokens (light-mode first) ──
        "surface":                    "#F8F9FF",
        "surface-bright":             "#F8F9FF",
        "surface-dim":                "#D4DAE7",
        "surface-container-lowest":   "#FFFFFF",
        "surface-container-low":      "#EEF4FF",
        "surface-container":          "#E7EEFB",
        "surface-container-high":     "#E2E8F5",
        "surface-container-highest":  "#DCE3F0",
        "background":                 "#F8F9FF",
        "on-background":              "#151C25",
        "on-surface":                 "#151C25",
        "on-surface-variant":         "#444933",
        "on-secondary-container":     "#656464",
        "primary":                    "#506600",
        "primary-container":          "#CCFF00",
        "primary-fixed":              "#C3F400",
        "primary-fixed-dim":          "#ABD600",
        "on-primary":                 "#FFFFFF",
        "on-primary-container":       "#5B7300",
        "on-primary-fixed":           "#161E00",
        "on-primary-fixed-variant":   "#3C4D00",
        "inverse-primary":            "#ABD600",
        "secondary":                  "#5F5E5E",
        "secondary-container":        "#E5E2E1",
        "on-secondary":               "#FFFFFF",
        "on-secondary-fixed":         "#1C1B1B",
        "secondary-fixed-dim":        "#C9C6C5",
        "tertiary":                   "#585F6A",
        "tertiary-container":         "#E6EDFA",
        "tertiary-fixed":             "#DCE3F0",
        "tertiary-fixed-dim":         "#C0C7D3",
        "on-tertiary":                "#FFFFFF",
        "on-tertiary-container":      "#646B76",
        "on-tertiary-fixed":          "#151C25",
        "on-tertiary-fixed-variant":  "#404752",
        "outline":                    "#747A60",
        "outline-variant":            "#C4C9AC",
        "error":                      "#BA1A1A",
        "error-container":            "#FFDAD6",
        "on-error":                   "#FFFFFF",
        "on-error-container":         "#93000A",
        "inverse-surface":            "#2A313B",
        "inverse-on-surface":         "#EAF1FE",
        "surface-tint":               "#506600",
        "surface-variant":            "#DCE3F0",
        // Convenience aliases
        "electric-lime":              "#CCFF00",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        display:  ["Space Grotesk", "sans-serif"],
        body:     ["Space Grotesk", "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
        space:    ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        full:    "0.75rem",
      },
    },
  },
  plugins: [],
};
